# Generated by Django 5.2.4 on 2025-07-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='deadline',
            field=models.DateField(help_text='last date to apply', null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(help_text='eg. 3 months, 6 months', max_length=100, null=True),
        ),
    ]
