# Generated by Django 5.2.4 on 2025-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_internship_deadline_alter_internship_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='deadline',
            field=models.DateField(help_text='last date to apply'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(help_text='eg. 3 months, 6 months', max_length=100),
        ),
    ]
