# Generated by Django 5.2.4 on 2025-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_internship_deadline_alter_internship_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[('1', 'Applied'), ('2', 'Accepted'), ('3', 'Rejected')], default=1, max_length=15),
        ),
    ]
