# Generated by Django 5.2.4 on 2025-07-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_alter_application_status'),
        ('users', '0003_alter_studentprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='users.studentprofile'),
        ),
    ]
